safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vendor']
include: ['CNAME', '.nojekyll']

url: https://15th-ndn-hackathon.named-data.net
baseurl:

plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

deadlines:
  - name: Registration deadline
    date: November 16, 2023
  - name: Project Submission deadline
    date: November 16, 2023
  - name: Acceptance notification
    date: November 16, 2023

# Configuration for permalink
permalink: /:page.html

# Configuration for site
title: 15th Named Data Networking (NDN) Hackathon
short_title: 15th NDN Hackathon
description: November 18-19, 2023, UCLA, CS building- UCLA Engineering VI, 3rd floor , LA, California
author: 15th NDN Hackathon Organizing Committee
#email: 13th-ndn-hackathon@named-data.net

# Configuration for blog
lang: en
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for navbar.html
navbar_list:
  - name: Home
    link: /
  - name: Committees
    link: /committees.html
  - name: Call for Hacks
    link: /cfh.html
  - name: HACKS
    link: /hacks.html
  - name: Program
    link: /program.html
  - name: Judging
    link: /judging.html
  - name: Code of Conduct
    link: /conduct.html
  - name: ">> REGISTER <<"
    link: https://www.eventbrite.com/e/736029894227?aff=oddtdtcreator

asides:
    github: true
    tweets: false
    archive_tabs: false

google_plus_one:
    size: medium

twitter:
    username: NamedData
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false
    widget_id: 698294519054278656

github:
   username: 14th-ndn-hackathon
   count: 10000

assets:
  cache: .sass-cache
  features:
    automatic_img_size: false
  sources:
    - assets/css
    - assets/images
    - assets/js

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/files

  autoprefixer:
    browsers:
      - defaults
