name: Build

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build
        run:
          bundle exec jekyll build --config _config.yml

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: _site
